# -*- coding: utf-8 -*-
"""chbmit-pre-processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dxLEM78KOTNU5Nx6Bd34VqN4MA8-kS8f
"""

import os
import re
import json
import time
import numpy as np
import mne

# CONFIG
INPUT_DIR = "//kaggle/input/datasets/abhishekinnvonix/seizure-epilepcy-chb-mit-eeg-dataset-pediatric/chb-mit-scalp-eeg-database-1.0.0"
OUTPUT_DIR = "/kaggle/working/chbmit_processed"
MANIFEST_PATH = os.path.join(OUTPUT_DIR, "manifest.json")

WINDOW_SEC = 4
FS = 256
WINDOW_SAMPLES = WINDOW_SEC * FS          # 1024 samples per window
SEIZURE_STRIDE_SEC = 2                    # 50% overlap for seizure windows
NORMAL_STRIDE_SEC = 4                     # no overlap for normal windows

PREICTAL_BUFFER_SEC = 300                 # exclude 5 min before/after seizure from normal pool
MAX_NORMAL_PER_SEIZURE = 5                # cap: at most 5x normal windows per seizure window
MAX_NORMAL_IF_NO_SEIZURE = 100            # cap for files with no seizures

INT16_SCALE = 100.0                       # ~0.01 microvolt precision (now correctly applied)
NOTCH_FREQ_HZ = 60.0                      # CHB-MIT recorded in the US -> 60Hz powerline

SEIZURE_OVERLAP_THRESHOLD = 0.5           # window must be >=50% ictal to be labeled seizure

CANONICAL_CHANNELS = [
    "FP1-F7", "F7-T7", "T7-P7", "P7-O1",
    "FP1-F3", "F3-C3", "C3-P3", "P3-O1",
    "FP2-F4", "F4-C4", "C4-P4", "P4-O2",
    "FP2-F8", "F8-T8", "T8-P8", "P8-O2",
    "FZ-CZ", "CZ-PZ", "P7-T7", "T7-FT9",
    "FT9-FT10", "FT10-T8"
]

os.makedirs(OUTPUT_DIR, exist_ok=True)

# MANIFEST
def load_manifest():
    if os.path.exists(MANIFEST_PATH):
        with open(MANIFEST_PATH, "r") as f:
            return json.load(f)
    return {"completed": [], "log": []}


def save_manifest(manifest):
    with open(MANIFEST_PATH, "w") as f:
        json.dump(manifest, f, indent=2)

# STEP 1: parse chbXX-summary.txt for filenames + seizure intervals

def parse_summary(subject):
    summary_path = os.path.join(INPUT_DIR, subject, f"{subject}-summary.txt")
    with open(summary_path, "r", errors="ignore") as f:
        text = f.read()

    files = {}
    current_file = None
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("File Name:"):
            current_file = line.split(":", 1)[1].strip()
            files[current_file] = {"seizures": []}
        elif current_file and "Seizure" in line and "Start Time" in line:
            match = re.search(r"(\d+)\s*seconds", line)
            if match:
                files[current_file].setdefault("_pending_start", []).append(int(match.group(1)))
        elif current_file and "Seizure" in line and "End Time" in line:
            match = re.search(r"(\d+)\s*seconds", line)
            if match and files[current_file].get("_pending_start"):
                start = files[current_file]["_pending_start"].pop(0)
                files[current_file]["seizures"].append((start, int(match.group(1))))
    for f in files.values():
        f.pop("_pending_start", None)
    return files

def preprocess_raw(subject, filename):
    edf_path = os.path.join(INPUT_DIR, subject, filename)
    raw = mne.io.read_raw_edf(edf_path, preload=True, verbose=False)

    if raw.info["sfreq"] != FS:
        print(f"    [resample] {raw.info['sfreq']}Hz -> {FS}Hz")
        raw.resample(FS, verbose=False)

    raw.rename_channels({ch: ch.strip().upper() for ch in raw.ch_names})

    # Detect and drop duplicate channels (e.g. two "T8-P8" entries), keeping
    # the first occurrence, then strip any leftover numeric suffixes so the
    # remaining channel matches the canonical name exactly.
    seen = set()
    drop = []
    for ch in raw.ch_names:
        base = re.sub(r'-\d+$', '', ch)
        if base in seen:
            drop.append(ch)
        else:
            seen.add(base)
    if drop:
        raw.drop_channels(drop)
        print(f"    [duplicates dropped] {drop}")

    raw.rename_channels({
        ch: re.sub(r'-\d+$', '', ch)
        for ch in raw.ch_names
        if re.search(r'-\d+$', ch)
    })

    canonical_upper = [ch.upper() for ch in CANONICAL_CHANNELS]
    available_upper = [ch for ch in canonical_upper if ch in raw.ch_names]
    n_available = len(available_upper)
    n_total_in_file = len(raw.ch_names)

    if n_available < 15:
        print(f"    [skip] only {n_available}/{len(canonical_upper)} canonical channels "
              f"(file has {n_total_in_file} total) — skipping")
        return None, [], n_available, n_total_in_file

    raw.pick(available_upper)
    selected_channels = list(raw.ch_names)

    raw.filter(
        l_freq=0.5, h_freq=40.0,
        method="iir",
        iir_params=dict(order=5, ftype="butter"),
        verbose=False
    )
    raw.notch_filter(
        freqs=NOTCH_FREQ_HZ,
        method="iir",
        iir_params=dict(order=4, ftype="butter"),
        verbose=False
    )


    data = raw.get_data(units="uV")
    return data, selected_channels, n_available, n_total_in_file

# STEP 3: windowing — sample-level masks, seizure overlap threshold
def make_windows(data, seizures, subject, filename, fs=FS):
    n_channels, n_samples = data.shape

    ictal_mask = np.zeros(n_samples, dtype=bool)
    exclude_mask = np.zeros(n_samples, dtype=bool)

    for start_sec, end_sec in seizures:
        start_s = min(int(start_sec * fs), n_samples)
        end_s = min(int(end_sec * fs), n_samples)
        ictal_mask[start_s:end_s] = True
        buf_start_s = max(0, int((start_sec - PREICTAL_BUFFER_SEC) * fs))
        buf_end_s = min(n_samples, int((end_sec + PREICTAL_BUFFER_SEC) * fs))
        exclude_mask[buf_start_s:buf_end_s] = True

    min_overlap_samples = int(WINDOW_SAMPLES * SEIZURE_OVERLAP_THRESHOLD)

    seizure_windows = []
    seizure_meta = []
    if seizures:
        stride = SEIZURE_STRIDE_SEC * fs
        for start_s in range(0, n_samples - WINDOW_SAMPLES, stride):
            end_s = start_s + WINDOW_SAMPLES
            window = data[:, start_s:end_s]
            if window.shape[1] != WINDOW_SAMPLES:
                continue
            overlap = int(ictal_mask[start_s:end_s].sum())
            if overlap >= min_overlap_samples:
                seizure_windows.append(window)
                seizure_meta.append({
                    "subject": subject, "file": filename,
                    "start_sample": int(start_s), "end_sample": int(end_s),
                    "label": 1, "overlap_samples": overlap,
                })

    normal_candidates = []
    normal_meta_candidates = []
    stride = NORMAL_STRIDE_SEC * fs
    for start_s in range(0, n_samples - WINDOW_SAMPLES, stride):
        end_s = start_s + WINDOW_SAMPLES
        window = data[:, start_s:end_s]
        if window.shape[1] != WINDOW_SAMPLES:
            continue
        if not exclude_mask[start_s:end_s].any():
            normal_candidates.append(window)
            normal_meta_candidates.append({
                "subject": subject, "file": filename,
                "start_sample": int(start_s), "end_sample": int(end_s),
                "label": 0, "overlap_samples": 0,
            })

    n_seizure = len(seizure_windows)
    cap = n_seizure * MAX_NORMAL_PER_SEIZURE if n_seizure > 0 else MAX_NORMAL_IF_NO_SEIZURE
    if len(normal_candidates) > cap:
        idx = np.linspace(0, len(normal_candidates) - 1, cap).astype(int)
        normal_windows = [normal_candidates[i] for i in idx]
        normal_meta = [normal_meta_candidates[i] for i in idx]
    else:
        normal_windows = normal_candidates
        normal_meta = normal_meta_candidates

    def to_int16(windows):
        if not windows:
            return np.empty((0, n_channels, WINDOW_SAMPLES), dtype=np.int16)
        arr = np.stack(windows).astype(np.float32) * INT16_SCALE
        return np.clip(arr, -32000, 32000).astype(np.int16)

    return to_int16(seizure_windows), to_int16(normal_windows), seizure_meta, normal_meta

# MAIN LOOP
def process_subject(subject, manifest):
    print(f"\n{'='*50}")
    print(f"  SUBJECT: {subject}")
    print(f"{'='*50}")

    file_info = parse_summary(subject)
    subject_dir = os.path.join(OUTPUT_DIR, subject)
    os.makedirs(subject_dir, exist_ok=True)

    for filename, info in file_info.items():
        key = f"{subject}/{filename}"
        if key in manifest["completed"]:
            print(f"  [skip] {filename} already done")
            continue

        edf_path = os.path.join(INPUT_DIR, subject, filename)
        if not os.path.exists(edf_path):
            print(f"  [missing] {filename} not found in input — skipping")
            continue

        try:
            t0 = time.time()
            print(f"\n  [process] {filename}")

            result, selected_channels, n_ch_available, n_ch_total = preprocess_raw(subject, filename)
            t1 = time.time()
            print(f"    preprocess: {t1-t0:.1f}s | channels: {n_ch_available}/{len(CANONICAL_CHANNELS)} "
                  f"(file has {n_ch_total} total)")

            if result is None:
                manifest["completed"].append(key)
                manifest["log"].append({
                    "file": key, "status": "skipped_channels",
                    "channels_available": n_ch_available, "channels_total": n_ch_total,
                })
                save_manifest(manifest)
                continue

            data = result
            seizures = info.get("seizures", [])
            print(f"    seizures: {len(seizures)} {seizures if seizures else '(none)'}")

            seizure_windows, normal_windows, seizure_meta, normal_meta = make_windows(
                data, seizures, subject, filename
            )
            t2 = time.time()
            print(f"    windowing: {t2-t1:.1f}s | seizure={seizure_windows.shape[0]} "
                  f"normal={normal_windows.shape[0]}")

            out_path = os.path.join(subject_dir, f"{filename.replace('.edf', '')}.npz")
            np.savez_compressed(
                out_path,
                seizure_windows=seizure_windows,
                normal_windows=normal_windows,
                selected_channels=np.array(selected_channels),
                seizure_meta=np.array(json.dumps(seizure_meta)),
                normal_meta=np.array(json.dumps(normal_meta)),
                scale_factor=np.float32(INT16_SCALE),
                subject=subject,
                filename=filename,
                n_seizure_events=len(seizures),
                window_sec=WINDOW_SEC,
                fs=FS,
            )
            t3 = time.time()
            size_mb = os.path.getsize(out_path) / (1024 * 1024)
            print(f"    save: {t3-t2:.1f}s | size: {size_mb:.2f} MB | TOTAL: {t3-t0:.1f}s")

            # AUTOMATIC SANITY CHECK — catches degenerate/all-zero data immediately,
            # so this exact bug can never silently slip through again.
            check = np.load(out_path, allow_pickle=True)
            has_normal = check["normal_windows"].shape[0] > 0
            has_seizure = check["seizure_windows"].shape[0] > 0
            if has_normal:
                nz = check["normal_windows"]
                print(f"  [sanity check] normal_windows: min={nz.min()} max={nz.max()} "
                      f"std={nz.std():.2f} {'*** ALL ZERO — BUG! ***' if nz.std() == 0 else '(OK)'}")
            if has_seizure:
                sz = check["seizure_windows"]
                print(f"  [sanity check] seizure_windows: min={sz.min()} max={sz.max()} "
                      f"std={sz.std():.2f} {'*** ALL ZERO — BUG! ***' if sz.std() == 0 else '(OK)'}")

            manifest["completed"].append(key)
            manifest["log"].append({
                "file": key, "status": "ok",
                "seizure_windows": int(seizure_windows.shape[0]),
                "normal_windows": int(normal_windows.shape[0]),
                "seizure_events": len(seizures),
                "channels_used": n_ch_available,
                "channels_total": n_ch_total,
                "selected_channels": selected_channels,
            })
            save_manifest(manifest)

        except Exception as e:
            print(f"  [ERROR] {filename}: {e}")
            continue

# LOADER — use at training time, NOT during preprocessing
def compute_normalization_stats(npz_paths):
    """Compute per-channel mean/std across TRAINING files only. Reuse on test."""
    all_windows = []
    for path in npz_paths:
        d = np.load(path, allow_pickle=True)
        scale = float(d["scale_factor"])
        s = d["seizure_windows"].astype(np.float32) / scale
        n = d["normal_windows"].astype(np.float32) / scale
        if s.shape[0] > 0:
            all_windows.append(s)
        if n.shape[0] > 0:
            all_windows.append(n)
    all_data = np.concatenate(all_windows, axis=0)
    mean = all_data.mean(axis=(0, 2), keepdims=True)
    std = all_data.std(axis=(0, 2), keepdims=True) + 1e-8
    return {"mean": mean, "std": std}


def load_and_normalize(npz_path, stats=None):
    """
    Load a .npz and apply z-score normalization.
    stats=None -> compute from this file only (quick test, NOT for paper experiments).
    """
    d = np.load(npz_path, allow_pickle=True)
    scale = float(d["scale_factor"])
    s = d["seizure_windows"].astype(np.float32) / scale
    n = d["normal_windows"].astype(np.float32) / scale

    selected_channels = list(d["selected_channels"])
    seizure_meta = json.loads(str(d["seizure_meta"])) if "seizure_meta" in d else []
    normal_meta = json.loads(str(d["normal_meta"])) if "normal_meta" in d else []

    if stats is None:
        all_data = np.concatenate([s, n], axis=0) if (s.shape[0] and n.shape[0]) else (
            s if s.shape[0] else n)
        mean = all_data.mean(axis=(0, 2), keepdims=True)
        std = all_data.std(axis=(0, 2), keepdims=True) + 1e-8
    else:
        mean, std = stats["mean"], stats["std"]

    s_norm = (s - mean) / std if s.shape[0] else s
    n_norm = (n - mean) / std if n.shape[0] else n
    return s_norm, n_norm, seizure_meta, normal_meta, selected_channels


def print_summary(manifest):
    print("\n" + "=" * 50)
    print("PREPROCESSING SUMMARY")
    print("=" * 50)
    ok = [e for e in manifest["log"] if e.get("status") == "ok"]
    skipped = [e for e in manifest["log"] if e.get("status") == "skipped_channels"]
    total_s = sum(e.get("seizure_windows", 0) for e in ok)
    total_n = sum(e.get("normal_windows", 0) for e in ok)
    print(f"Files processed:              {len(ok)}")
    print(f"Files skipped (ch mismatch):  {len(skipped)}")
    print(f"Total seizure windows:        {total_s}")
    print(f"Total normal windows:         {total_n}")
    if total_s:
        print(f"Seizure:Normal ratio:         1:{total_n // total_s}")
    print("=" * 50)

if __name__ == "__main__":
    manifest = load_manifest()

    all_subjects = [f"chb{str(i).zfill(2)}" for i in range(1, 25)]

    SUBJECTS = all_subjects

    for subject in SUBJECTS:
        process_subject(subject, manifest)

    print_summary(manifest)
    print(f"\nDone. Output saved in {OUTPUT_DIR}")